name: dingtalk_robot
description: Unofficial Dart SDK for Dingtalk Enterprise Robot.
version: 0.1.2
repository: https://github.com/djbird2046/dingtalk_robot

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  json_annotation: ^4.9.0
  http: ^1.3.0
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  crypto: ^3.0.6
  logging: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.9
  lints: ^5.0.0
  test: ^1.24.0
